### ISSUE TITLE
M3 Deliverables 

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fair-squares#124]
Deliverables [M3](https://github.com/Fair-Squares/Grants-Program/blob/master/applications/fair_squares.md#milestone-3---bidding-mechanism)

**Documentation / Articles**
- [x] Testing Guide 
- [x] Article
- [x] Inline documentation
- [ ] Tutorial M3
- [x] grants delivery: [link](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/fair_squares-milestone-3.md)

**Pallets**
- [ ] bidding pallet
  - [ ] all functionality in #123
  - [ ] unit testing
  - [ ] integration testing with housing-fund & fractioning
  - [ ] benchmarks

**Modules**
- [ ] timer
  - [ ] Implement epoch #123
  - [ ] unit testing
  - [ ] integration testing hooks activted 
  - [ ] benchmarks

- [x] fractioning
  - [x] Implement epoch #123
  - [x] unit testing
  - [x] integration testing linking fractioning to nft
  - [ ] benchmarks

**Formatting,Linting, testing**
- [ ] cargo-fmt
- [ ] cargo-clippy
- [ ] test with Polkadot.js

**Comment by ndkazu** [comment]
I think fractioning should be a pallet in the end:
- It will be a customised version of the assets pallet
- It will manage the transfer of ownership tokens
Maybe we should even re-think the name, as it is not simply fractionning ownership, but it is actually managing ownership.

**Comment by ilhanu** [comment]
Agreed, will all points will change the issues

On the naming part, think share-distributor is decent, as that is the only thing it does.
