### ISSUE TITLE
Create an epoch time-frame of 20 mins.

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fair-squares#125]

**Comment by ndkazu** [comment]
It appears that the way to set the epoch length is to use the Babe pallet in the runtime.
Unfortunately this pallet is interconnected with almost all the pallets in the substrate/frame, and a few other libaries.
there might be a simpler way, but I couldn't find it.
Right now I'm in the process of adding necessary pallets & imports one by one, but if that really is the way, we're better off directly using the substrate/node runtime and ALL the pallets directly.

**Comment by ndkazu** [comment]
Maybe we should write down the goal of this task. Depending on it, the `TimeStamp pallet` might be sufficient for this task.

**Comment by ilhanu** [comment]
I would say it's the implementation of the session pallet. 
https://github.com/paritytech/substrate/blob/master/frame/session/src/lib.rs

```
//! - **Session:** A session is a period of time that has a constant set of validators. Validators
//!   can only join or exit the validator set at a session change. It is measured in block numbers.
//!   The block where a session is ended is determined by the `ShouldEndSession` trait. When the
//!   session is ending, a new validator set can be chosen by `OnSessionEnding` implementations.
```
The session-pallet is integrated with the staking pallet, but we can re-use the pallet solely for session logic for calculating the sessions change and it emits the event we require.

**Comment by ndkazu** [comment]
I've configured the runtime, now working on the corresponding chainspec configuration. will commit something the moment I have something that compile.

**Comment by ndkazu** [comment]
Configured the runtime for a 20min Epoch, but it can be changed in the constant.rs file located in the runtime folder.
created a branch as shown in github notifications.
