### ISSUE TITLE
Implement asset-distributor-pallet (fungible) + config shares that get minted

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fair-squares#126]

**Comment by ndkazu** [comment]
**Workflow, part1:**
![alt text](https://github.com/ndkazu/Kaz_Fair_square/blob/571133a9e2f9f6c5c0547a7547a4af3579ecdc6c/workflow_p1.png?raw=true)


**Workflow, part2:**
![alt text](https://github.com/ndkazu/Kaz_Fair_square/blob/571133a9e2f9f6c5c0547a7547a4af3579ecdc6c/workflow_p2.png?raw=true)
