### ISSUE TITLE
Onboarding pallet - Get houses with onboarded status

### ISSUE THREAD

**Issue by letodunc** [Fair-Squares/fair-squares#137]
**Motivation**

_The Bidding pallet checks houses in the Onboarding pallet with the `onboarded` status to process them. The actual exposed storage `houses` doesn't allow to get a vector of houses directly or the usage of iterator to get houses._

**Suggested Solution**

Expose a new function to get the houses with `onboarded` status so the Bidding pallet can manage them in its workflow.

**Function**

- **get_onboarded_houses()**: returns entries from the storage `Houses` (exposed as `houses`) that contains assets with `onboarded` status

Update tests to cover the new function.

**Comment by ndkazu** [comment]
A simpler solution would be to upgrade the House 'StorageDoubleMap` to a `IterableStorageDoubleMap`.

**Comment by letodunc** [comment]
The iteration is available with the current type. The problem that arises is that retrieving data from outside the pallet requires going through the ``houses`` getter which must have arguments. The solution allows to retrieve the houses without any arguments.

**Comment by ilhanu** [comment]
Think the storages and the output of housing and proposal status is eventually going to be refactored , remember the extract of the query of a proposal. I think this getter is good to get us started also an easier entry for a front-end and users.
