### ISSUE TITLE
Housing fund pallet - update exposed functionalities

### ISSUE THREAD

**Issue by letodunc** [Fair-Squares/fair-squares#144]
**Motivation**

_The Bidding pallet need to have the contributions stored in the Housing fund for its process. The storagemap storing the contributions in Housing fund pallet doesn't allow to get a list of data from Bidding pallet's call. The `house_bidding` method need to be callable from Bidding pallet to complete its workflow. It should manage the Nft ids in its workflow._

**Suggested Solution**

Expose a new function to get the contributions ordered from oldest to newest.
Update 
 -  `house_bidding` to be a public method but no more a callable method (should not remain under the `#[pallet::call]` macro) and manage Nft ids (`NftCollectionId` and `NftItemId`).
 - `FundOperation` struct to keep track of the asset

**Functions**

 - get_contributions(): returns entries from the storage `Contributions`.

Update tests to cover the new function and the updated function.

**Comment by ndkazu** [comment]
Awesome! I was about to ask for this "contributions storage" functionality. If completed, the related PR should be merged before PR #145.
