### ISSUE TITLE
Pallet share_distributor Virtual account

### ISSUE THREAD

**Issue by ndkazu** [Fair-Squares/fair-squares#145]
**Motivation**

Implement the creation of a virtual account based on the asset's collection_id and item_id

**Suggested Solution**

- [x] 1 struct : `Ownership{virtual_account: T::AccountId, owners: Vec<T::AccountId>}`
- [x] 1 Storage double map :  `Virtual(T::NftCollectionId,T::NftItemId,Ownership<T>)`
- [x] 1 event : `VirtualCreated{account: T::AccountId, collection:T::NftCollectionId,item: T::NftItemId}`
- [x] 1 error :  `ReservedToServicer`
- [x] 1 helper function : `fn virtual_account(collection_id: T::NftCollectionId, item_id: T::NftItemId)`
- [x] 1 pallet call : `fn create_virtual(origin: OriginFor<T>, collection_id: T::NftCollectionId, item_id: T::NftItemId)`

![alt text](https://github.com/ndkazu/Kaz_Fair_square/blob/571133a9e2f9f6c5c0547a7547a4af3579ecdc6c/workflow_p1.png?raw=true)

**Comment by letodunc** [comment]
Is it the bidding pallet that makes calls to he share distributor pallet?

**Comment by ndkazu** [comment]
> Is it the bidding pallet that makes calls to he share distributor pallet?

Hey steph, 
Yes, the idea is that for 1 asset, the bidding pallet makes 1 unique call with the 3 parameters: `collection_id` ,`item_id` , `owners_list`. From there the bidding pallet takes care of the rest.

**Comment by letodunc** [comment]
Ok, I see. Maybe the call made by the `bidding` pallet could be done via a non callable function (not under the `#[pallet::call]` macro) with no need of signed origin as the bidding pallet has no account associated with the `servicer` role. Actually it will need an account to make a call to the `share distributor` pallet. In the process, the owner list is stored in the housing fund pallet when the `housing_bidding()` function is called by the `bidding` pallet.

**Comment by ndkazu** [comment]
> Ok, I see. Maybe the call made by the `bidding` pallet could be done via a non callable function (not under the `#[pallet::call]` macro) with no need of signed origin as the bidding pallet has no account associated with the `servicer` role. Actually it will need an account to make a call to the `share distributor` pallet. In the process, the owner list is stored in the housing fund pallet when the `housing_bidding()` function is called by the `bidding` pallet.

This is a valid and interesting point that I discussed with Ilhan before: We might need an "almighty" virtual account defined in the runtime, that wil execute calls on all pallets, and maybe make a new role (Admin? ) for this account.

**Comment by ilhanu** [comment]
Can't we implement a special origin ? https://docs.substrate.io/build/origins/
We don't want specific actions that are configured in our runtime to be associated with the roles we have set for the users.

**Comment by ndkazu** [comment]
> Can't we implement a special origin ? https://docs.substrate.io/build/origins/ We don't want specific actions that are configured in our runtime to be associated with the roles we have set for the users.

so we would use the following for the caller (and remove the servicer check)?
// Root
`(system::RawOrigin::Root.into()`

**Comment by letodunc** [comment]
So in `bidding` pallet will make call to `share distributor` pallet function with root account. The 144 and 145 need to be merged into main before continuing with the bidding pallet.

**Comment by ndkazu** [comment]
I will update #145 with the Root check first then I will merge.
