### ISSUE TITLE
To_Do list discuss and expand

### ISSUE THREAD

**Issue by ndkazu** [Fair-Squares/fair-squares#15]
**Needed Additional Features**

_- Loose coupling of Litentry NFT pallet_
_- Add fractional nft function in Fairsquares pallet_
_- Rewrite FairSquares pallet around Litentry nft pallet, instead of Anmol nft pallet_
_- Voting system for a proposal approval (https://docs.substrate.io/rustdocs/latest/pallet_collective/index.html)._
_- Proposal destruction function (proposal not approved, or expired projects)_
_- Design & Implementation of the logic behind the choice of the contributors for each proposal_
_- Design & Implementation of the rent payment logic._

**Comment by ilhanu** [comment]
Closed this as most issues #19 #20 #29 #28 #30 #25 have now their own tracking-issues
