### ISSUE TITLE
M4 Kick-off

### ISSUE THREAD

**Issue by ndkazu** [Fair-Squares/fair-squares#193]
**Motivation**
Discuss & decide the role & structure of  the Finaliser pallet, as well as the Representative role
Please, add diagrams and comments relevant to the discussion to this issue, instead of creating a new one (For now).

*Representative role summary*
![alt text](https://github.com/ndkazu/FS_update_929/blob/b32f370dc0aaa33afb58f4579b147757c6126a1e/representative.png?raw=true)

**To be discussed:**
- [x] Representative role extent
- [x] Representative Election process
- [x] Representative actions in the FS system(Tenants metadata modifications, Tenant status(to be established), etc...)

*Pallet_Finaliser*
![alt text](https://github.com/ndkazu/FS_update_929/blob/b32f370dc0aaa33afb58f4579b147757c6126a1e/bidding_and_Finaliser.png?raw=true)

**To be discussed:**
- [x] Notary role extent
- [x] Notary selection process
- [x] Notary actions in the FS system
- [x] Relation between Bidding and Finaliser pallets

**Additional topics**
- Tenants registry needed for M4?
- Which pallet will manage *potential_Tenants-Representative-Asset* operations?
- Which pallet will manage *Final_tenants-Asset-Landlords* operations?

**Comment by ilhanu** [comment]
After our first call we discussed the workflow of the requirements of M4. 

**Finalizer:**  

This feature is fulfilled in the real world by someone that has authority to pass housing titles and file them in the land titles registry. This is usually done by a notary and they have their own specific way of working. We don’t want to change that process, what we do require is a proof of documents / proof of passing when they come-up with a verdict. 

Requirements: 
- Has it's own role `notary`
- Provides a proof linking to the verdict ( this will be further clarified in the future )
- The asset that is has to review should be in  `Onboarded` state and should have an investors list reserved.
  - The sale cannot take place without the notary finalising the sale. 
  - The Status `Finalizing` is applied when the reserved list of investors and the asset is being finalized. 
  - When the status is `finalizing` we don't want to `bidding-pallet` to reserve a new investors list. The asset should essentially be locked. 
- The notary may decide a couple of things
  - Accept the sale, which means the bidding-pallet can continue with the happy flow and start the exchange. This would change the status to `purchased` of the asset. We can let this transition happen by introducing a new status to the asset or adding a new variable for the acceptation so its `finalizing + verified --> purchased`. 
  - Decline the sale to happen for various reasons such as something wrong with the asset or they identified fraudulent behaviour etc. The rejection has two degrees. 
  - If there is any behaviour that is fraudulent and the proposal is to be destroyed. The investors would get their allocation in the asset unreserved. If it's the asset the asset should get a new status `REJECTED` or `Slashed` depending on the severity.
  - If there is something found about on or more investors, the housing status should be demoted to `Onboarded` and the investors should get their allocation unreserved. So there is a new round again. This would mean that the investor that is found to be fraudulent would not be able to participate in the next round. So we would need to give investors also a status. [Verified, Under-Review, Rejected] ?


**Owners-vote:**

This feature is fulfilled in the real world by a vote of the owners of the building. We want to owners (shareholders) to be able to vote on anything regarding governance of the asset. This is can be Maintainance, Deciding if a tentant should be allowed, Selecting a representative.  

One of their duties is selecting a representative, why we want to have a `representative` role ? As the representative is the first point of contact for the owners and the tenant. More on this in the the next section. This part is about allowing the owners to govern their asset on chain. 

Requirements:
- Using the democracy pallet voting and tallying mechanism while relying on the assets-pallets shares for a specific unique asset.
- The first feature is `appointRepresentative` which allows the owners to appoint a representative. This is a one time action and you can't select multiple representatives.
- The asset should be in `Purchased` state. 


Structure:
- Integrated in voting pallet, with a prefix of `owners`
- Hide the democracy pallet from the UI/polkadot.js if possible (nice to have)


**Representative:**

The representative is the first point of contact for the owners and the tenant.

- The Representative  has a role `representative` and has a unique identifier for the unique asset it's representing.
- Add to the unique asset a `representative` field, which is a `AccountId`
- The representative might need to accept the role after `appointRepresentative` is called.
