### ISSUE TITLE
Code review & Bug fix

### ISSUE THREAD

**Issue by cuteolaf** [Fair-Squares/fair-squares#194]
Let us review the entire code base and fix all the issues before we kick off M4 development.

**List of issues:**

**`pallet_roles`**
- [x] `TotalMembers` should be increased if and only if the `account approval` is successful.
https://github.com/Fair-Squares/fair-squares/blob/5ac0058e3b2b302493d781ae99722f8c7e0fcf35/pallets/roles/src/lib.rs#L269-L270
- [ ] Optimize the flow of account creation request & approval
We have three different lists for account creation approval - `seller`s, `servicer`s and `notary`s.
Current implementation is not optimized in terms of time complexity.

**`pallet_housing_fund`**

- [ ] Clearly define the use of `MinContribution`
    In the current implementation, it works as the minimum amount per contribution.

- [ ] Declare `MinContribution` as a constant.
    Regarding the future development for the front-end UI, we should be able to fetch the value of `MinContribuiton` from the runtime.

- [ ] `MaxFundContribution` is not used.

**`pallet_onboarding`**

**`pallet_bidding`**
- [ ] Reduce the time complexity of `get_eligible_investors_contribution`
https://github.com/Fair-Squares/fair-squares/blob/471e031e79abf55f8c0d777e2b09d5ad21c3cdef/pallets/bidding/src/lib.rs#L445-L490

**Comment by cuteolaf** [comment]
`pallet_roles`

- [ ] `TotalMembers` should be increased if and only if the `account approval` is successful.

**Comment by cuteolaf** [comment]
`pallet_housing_fund`

- [ ] Clearly define the use of `MinContribution`
    In the current implementation, it works as the minimum amount per contribution.

- [ ] Declare `MinContribution` as a constant.
    Regarding the future development for the front-end UI, we should be able to fetch the value of `MinContribuiton` from the runtime.

- [ ] `MaxFundContribution` is not used.

**Comment by cuteolaf** [comment]
`pallet_onboarding`

- [ ] `PropoosalFee`


- How is it used in the pallet?
https://github.com/Fair-Squares/fair-squares/blob/5ac0058e3b2b302493d781ae99722f8c7e0fcf35/pallets/onboarding/src/lib.rs#L464-L466

- `ProposalFee` configuration in the runtime
https://github.com/Fair-Squares/fair-squares/blob/5ac0058e3b2b302493d781ae99722f8c7e0fcf35/runtime/src/lib.rs#L799

**Comment by cuteolaf** [comment]
> `pallet_roles`
> 
> * [ ]  `TotalMembers` should be increased if and only if the `account approval` is successful.
>   https://github.com/Fair-Squares/fair-squares/blob/5ac0058e3b2b302493d781ae99722f8c7e0fcf35/pallets/roles/src/lib.rs#L269-L270

https://github.com/Fair-Squares/fair-squares/pull/195

**Comment by ndkazu** [comment]
> `pallet_onboarding`
> 
> * [x]  `PropoosalFee`
> * How is it used in the pallet?
>   https://github.com/Fair-Squares/fair-squares/blob/5ac0058e3b2b302493d781ae99722f8c7e0fcf35/pallets/onboarding/src/lib.rs#L464-L466
> * `ProposalFee` configuration in the runtime
>   https://github.com/Fair-Squares/fair-squares/blob/5ac0058e3b2b302493d781ae99722f8c7e0fcf35/runtime/src/lib.rs#L799

I remembered this one. I first went with a fixed fee of 50$, but after discussion with the team, we decided to go with  percentage of the proposal price. the proposalFee is therefore supposed to be a percentage that we can adjust in the runtime. I did the necessary corrections an it is now a 10% fee.
