### ISSUE TITLE
Add new roles and permissions

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fair-squares#196]
Add new roles and permission, the actions these new roles can have are currently limited to the below list of actions. 

1. Notary (can finalize the sale)

```mermaid
graph LR
A[Asset]-- reserved -->B[Notary]
B --> C[Finalize]
C-- purchased -->D[Asset]
```
The notary can finalize the sale and the asset will be `purchased`. Also the notary can reject the sale and the asset will be back to the `rejected` state and the owner can decide to `sell` it or to `delist` the asset.

The cost for the notary will be paid from the bond the seller proposed.  

2. Representative (can propose a tenant)
```mermaid
graph LR
A[Asset]-- purchased -->B[Representative]
B --> C[Propose Tenant]
C-- accepted -->D[Asset]
```
The `representative` can propose a `tenant` and the owners can vote on it. The cost for the representative will be paid from the virtual account, which is the account that holds the funds for the asset and is of the owners.

3. Owners (can vote on governance)
```mermaid
graph LR
A[Asset]-- purchased -->B[Owners]
B --> C[Vote]
C-- tally -->D[Asset]
```
The owners are the investors, what makes the distinction is that they own asset of the specific unique asset. 

Currently the only flow we are implementing is the appointing of a representative. The owners can vote on it and the tally will be done by the democracy pallet. The cost for the owners will be paid from the virtual account, which is the account that holds the funds for the asset and is of the owners.

**Comment by ndkazu** [comment]
*Note:*
- Permissions mainly correspond to NFT_metada modifications, and are in most cases defined in the `nft_pallet`.
- Roles of course are defined in the `roles_pallet`
