### ISSUE TITLE
Propose a tentant 

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fair-squares#216]
One thing that is still outstanding is the representative role actions. 

We have defined in M4 grant application that the representative is able to propose/match a tentant. In M5 we will build a pool for the tentants to register, currently we will shortcut this by using a dummy tentant object either in the genesis-config or when the chain is running. 

Both the representative and the tenant roles are defined [here](https://github.com/Fair-Squares/fair-squares/blob/main/pallets/roles/src/types.rs#L138-L208):

1. We want the feature that the representative is allowed to propose a democracy proposal to the owners of an asset, linking to only the tentant. This will be notified to the owners that are able to vote on it. This ties in with #215 that is in the works right now. 
2. If the vote is successful we want to store in the asset-id the new tenants accountId that it is the accepted current Tenant. 

Further logic about payment streams and logic of the tentant matching is addressed in M5.

**Comment by cuteolaf** [comment]
EDGE CASES
- [ ] Someone without the `REPRESENTATIVE` role proposes a tenant
- [ ] A representative proposes a tenant for an asset that is not under control of him/her.
- [ ] A representative proposes someone without the `TENANT` role
- [ ] A representative proposed a tenant for an asset, but the asset is already linked to a tenant
- [ ] A representative proposes a tenant who is already linked with an asset
