### ISSUE TITLE
contribution & withdrawal of funds

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fair-squares#23]
The contribution flow of adding capital to the housing fund

1. Users once verified can contribute stable token to the housing fund.
1. Funding
2.1. The users fund stays in the fund and is registered in the fund with their contribution `amount` and `blockNr`.
2.2 The users that wan't to take out a full amount or a part of their capital are allowed, the register of `totalCapitalBonded` will be updated
1. The `fs-allocator` will define for all contributions when bidding on an asset, whose funds and how much of the funds will be taken along. More on this in future issue
Bidding succes?
1.  If the bid is successful the funds are converted into fractionalized shares of a house. 
Bidding fails? 
1. When the bid fails and is not sold to FS investors, then the funds are returned and investors are still first in line when a new asset is listed

**open questions:**
- How to deal with several contributions for the `fs-allocator`

**Comment by ndkazu** [comment]
Finalized the design of the contribution storage, and its associated structs/trait in the branch structure_template.
Next step is to design a user's account storage. I prepared an enum in the lib.rs which contains the structs representing the different roles:
```
 enum User{
      Investor,
      Tenant,
      HouseOwner,
   }
```
I want to use this enum in a storageMap "User" where the key will be the accountId, and the value will be an enum containing one of the roles.
