### ISSUE TITLE
Tenancy Pallet

### ISSUE THREAD

**Issue by ndkazu** [Fair-Squares/fair-squares#233]
#**Motivation**

This pallet will manage the relationship between the tenants and the representative:
- Detailed profile information submitted by the Tenant
- Asset request by a Tenant
- Tenant request & information review/Judgment by the Representative
- Several updates are needed in `asset_management` pallet

The Judgment result is sent to the asset owners when the representative starts a tenant session

**Suggested Solution**

*****Extrinsic:*****
- [x] `request_asset` : Will use Identity pallet's `set_identity` & `request_judgment`
- [x] `process_request`: use `provide_judgment` from identity, and start a referendum through `tenant_session` in Asset_management.
- [x] We must add `add_registrar` in the `asset_management` pallet call that is executed after a positive referendum to elect a representative.
- [x] Add `registrar_index` as a field to the representative struct.
- [x] Use orml-payment as inspiration for payments-pallet in FS (see issue #236 )
- [x] Add ROR in Asset_management runtime (see issue #232)
- [x] Add Guaranty Deposit coefficient in Asset_management (G.D.C:1,2,or 3 months) in Runtime
- In asset_Management Pallet:
- [ ] the Positive result of a Tenant referendum launch by the Representative should only trigger a payment request for a guaranty deposit which is calculated using the GDC and ROR (**[ROR x Asset_Price x GDC]/12 months**).
- [x] Guaranty deposit payment triggers the connection of the tenant to the asset, and updates the Rent in Tenant struct based on the ROR (**[ROR x Asset_Price]/12 months**).
- [ ] Guaranty deposit payment_request is triggered by a positive vote of the owners, concerning a new Tenant.
- [x] Update rent in tenant struct based on ROR once the tenant is accepted
- [ ] Add `request_guaranty_payment` in pallet `asset_management`
- [ ] Add `request_rent_payment` in pallet `asset_management`
- [ ] Add `accept_and pay` in the tenancy pallet in order to allow a tenant to process payment requests

*****Types:*****
- [x] `RegisteredTenant`: contains `user_infos` submitted to the Identity pallet and other useful fields.

*****Storage:*****
- [x] StorageMap: {`Tenant_id:RegisteredTenant`}.

**Comment by cuteolaf** [comment]
@ndkazu Why do we need `registrar_index` in the Representative struct?

**Comment by cuteolaf** [comment]
@ndkazu Do we really need to keep `registrar_index` in the `Representative` struct?
