### ISSUE TITLE
Onboarding an estate as an asset

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fair-squares#30]
We want FS to be permission-less, but still trustworthy. Therefore we want to use specific standard and identification ways that are [being standardised](https://drive.google.com/file/d/13OjoTK55hqov8qd9u3Kzn_jdsr1J88pG/view) by industry. Before getting there we need to have. 

**For now** we would assume that the roles are honest players and verified we will make use for this role will be integrated with the #19 an estate agent or house owner, that can onboard a house. The inputs required:

- Unique ID generated by the system for the object [increasing `assetId`]
- House owners [`accountId`]
- When you want the sale to happen[ `blockNr`]
- Province ( something about the location ? )
- Square meters [Tied to a global parameter to `pricePerSqm`]
- Deposit for onboarding `onboardingDeposit`

This generates/mint's an NFT with the current representative the estate agent and the owner the estate owner. The value of the house will be generated based on`sqm*pricePerSqm`.

The lifecycle of the NFT could be a maximum duration [`lifetimeNft`] that is a configurable constant, e.g. 2 weeks. If nothing happens with the onboarded asset, the nft get's burned and the deposit is transferred to the treasury. 

Simplified sequence diagram
```mermaid
sequenceDiagram
    participant houseOwner
    participant onboarder
    participant registry
    participant house
    Note over houseOwner,onboarder: can be same person
    onboarder->>registry: enters [ 'Sqm', 'locationData`, 'owner' ]
    registry->>house: generates a NFT with the data entered * Constants
    Note over registry,house: pricePerSqm=5000
    Note right of house: There will be an unique assert that has a base-price and it can be bid on by the housing fund
```

**Comment by MrishoLukamba** [comment]
The docs on nft pallet is not very clear. The nft classes and other stuffs.

**Comment by ilhanu** [comment]
You mean the docs of the Litentry nft pallet? @MrishoLukamba

**Comment by MrishoLukamba** [comment]
No orml-nft in dev branch. Am coupling it with this issue of onboarding asset because it requires to mint an NFT. But the documentation of using it and the uses of classes and other functionality not provided

**Comment by ilhanu** [comment]
Yeah, this because implementing orml_nft is essentially wrapping it in another module. You wouldn't use it directly (you'll actually notice that it doesn't have any Call methods exposed itself).

But if your on the `dev` branch you should have the Litentry Pallet already implemented and using the orml-nft module

**Comment by MrishoLukamba** [comment]
Yes ofcourse but what am asking is an explanation on key terms such as what is an nft class, and other defined struct. In high level. I can understand the code but what it actually mean in abstraction

**Comment by ilhanu** [comment]
I think your best shot for documentation is the original inline comments/docs of the [code](https://github.com/open-web3-stack/open-runtime-module-library/blob/master/nft/src/lib.rs).


Also looking for instance how other teams are using the orml-nft might help you further for example Acala, as some teams are also switching to the uniques pallet of ParityTech

**Comment by MrishoLukamba** [comment]
Sure will do

**Comment by MrishoLukamba** [comment]
And also. How can see the commit that closed last issues? And also in dev there isnt litentry pallet
