### ISSUE TITLE
Roles pallet

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fair-squares#36]
The roles pallet for now gives users the extrinsic to set their own role. The roles-pallet gives users the following roles to be implemented within M1. [investor, tentant, seller, servicer]. 

- [x] investor and tenant get the role immediately 
- [x] Seller and servicer can set the role themselves, but need judgement from a role verifier.

**Requirements:**

- [x] An account can only set one role ( defined in w3f grant)
- [x] The role verifier will provide judgement, for now this belongs to a different

**Testing** scenarios, not excluded to the 

- [x] #50
- [x] Getting several roles, unsuccessful
- [x] Getting role (seller, servicer) without verification, unsuccessful

**Comment by ilhanu** [comment]
#43 Is a part of this issues

**Comment by ndkazu** [comment]
I will work on the Benchmarking
