### ISSUE TITLE
Housing fund

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fair-squares#37]
Creating pallet-housing-fund

Config
- [ ] init accountId initiated at genesis. 

extrinsics
- [ ] Investors can deposit and withdraw their funds.
- [ ] fund registers which `accountId`, `amount`, and `blocknr` the funds were committed. 
- [ ] if a user withdraws any amount, it has the has_withdrawn `bool` activated 

query

- [ ] `contribution` of an investor keeps up the total per investors and it has withdrawn(bool) their accountId.
- [ ] housing_fund needs to have a getter for the total_funds.
   - [ ] Show total balance  (total transferable + contributed + reserved)
   - [ ] Show total transferable ( the available balance spendable)
   - [ ] Show contributed balance ( the withdraw able balance by the user and reservable by the housing fund)
   - [ ] Show total reserved (the users fund reserved by the housing fund)

**Comment by letodunc** [comment]
Here is a proposition to the housing_fund pallet structure.
### The housing_fund maintains the following informations:

- the amount of available fund
- the amount of reserved fund used for the house bidding
- the amount of contributed fund : the amount use to buy houses
- the total amount of the pot = amount available + reserved amount
- the history of accountId contribution to the pot. Each contribution contains the follwing informations:
  + accountId
  + blocknr : timestamp of the last account's operation (deposit, withdraw)
  + amount available (not used by the pallet to reserve or purchase a house)
  + amount reserved (used by the pallet to reserve a house)
  + amount contributed (used by the pallet to purchase a house), acts as a log
  + total balance = amount available + amount reserved
- the history of reserved fund, a list containing the data:
  + house identifier
  + price of the house
  + blocknr as timestamp of the reservation
  + list of contributions (AccountId, Amount) representing the share of each contributor in this reserved fund
    x => an entry is added to the reserved fund when a house bid occurs
    x => an entry is deleted from the reserved fund when
      * the house is bought
      * the house proposal  is refused : the fund is unreserved by Currency pallet (to be defined) and balance of available and reserved fund are to be updated for the general pot but also in the investors contributions
- the history of contributed fund used to purchase houses, a list containing the data:
  + house identifier
  + price of the house
  + blocknr as timestamp of the house purchase
  +list of contributions (AccountId, Amount) representing the share of each contributor in this purchase

The housing_fund pallet implements the **house_bidding** method.
The arguments are the following:
- the house identifier
- the price of the house
- a list of elements contaning
  + an accountId
  + the amount allocated by the accountId

These arguments respect thes conditions:
- the house price is equal to the sum of the amounts linked to the accountId
- the amount of each accountId must be <= of the available amount of the accountId's contribution
The following actions are taken at the method execution
- the price of the house is reserved from the fund with the Currency (generic term here, the currency's trait is to be defined) pallet
- the available and reserved funds should be updated accordingly for the housing_fund pot and the contribution of each account in the list
- the reserved history shoul be updated with new data: house identifier, house price, blocknr (as timestamp of reservation) and the list of accountIds contribution

The relationships between Available, Reserved and Contributed (terms that can be changed) funds are the following:
______________reserve_fund
Available <============> Reserved ------------> Contributed
______________unreserve_fund

**Comment by ilhanu** [comment]
> * total balance = amount available + amount reserved

This part I would leave out, user and front-end can make that computation. 

> the house price is equal to the sum of the amounts linked to the accountId

This would be actually house_price + house_treasury_balance, we will extended this function when working on the bidding-pallet. This applies to all functions, we will have constant 5%.  This constant is added on top of the price of the house.

For the rest I think it a very accurate description of the pallet
