### ISSUE TITLE
Flow of Fair Squares bidding and purchasing

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fair-squares#5]
**Motivation**

_The FS stakeholders arrive should a bid price based on the value of the house. Before an offer can be made on a house, it must be known with which investors and how much money per investor together the total bid is formed. The intention is that an offer must be made quickly and then it is up to the seller or authorised representative to make a choice._

**For the purpose of this hackathon we are going to keep it light and not make it hard as explained in the [Wiki](https://github.com/Fair-Squares/fair-squares/wiki/Features-of-Fair-Squares#bidding-and-purchase-engine), which would be the ideal implementation for better price and competitive markets** 

**Suggested Solution**

- [ ] Checking if there is enough $/€ in the housing fund, for a house that has the status **listed**
- [ ] Define which stakeholders/investors get selected for the house. 
  - [ ] If so, continue placing a bid with a +3% margin ( just a assumption) 
  - [ ] If bid is **successful** and get's accepted by the seller:
    - [ ] The house get the status `onboarded`
    - [ ] The investors get their part of the house as an fractionalized NFT
  - [ ] if bid is **unsuccessful** 
    - [ ] The house get's the status `rejected`
    - [ ] The investors selection returns to normal

**Additional Information**

This is the most novel part of the of the FS platform, willling to discuss. The above implementation is the most simple one, if we can implement this, we can always improve the realness of it. At the moment it might feel like abracadabra but this is the flow in simple steps.

**Comment by ndkazu** [comment]
Considering the use of the "Simple CrowdFund" model, a different workflow is suggested:
the following structs are available in the crowdfunding model:
- FundInfo: corresponds to a campaign for 1 house for example. the campaign goal (goal: balance) is therefore the house price+alpha. if the campaign is successful, the funds are used to buy the house in the form of a NFT with a multi-ownership logic.
-  A house NFT is minted at the beginning of a campaign. in case of campaign failure, the NFT is burned.

**Comment by ilhanu** [comment]
The flow when you try to crowdfund per house it's a more structured and that is what the `Simple Crowdfund` pallet does at the moment. 

But it's an obstacle for the usability of the platform. Cause the funding once it's like "fire and monitor" what your funding did, whereas you have to with fund each house specifically, it would be like having to do an transaction everyday or being a part of crowdloan daily or multiple per day if a protocol like this picks up.

The goal of it is that people put their funding in the fund and trust the mechanism of the platform/ protocol.

Customising the simple crowdfund: We would need to remove the `goal` and the `end-block` it's a black hole that will take all the funds, while still `withdrawable` when unused.

The beneficiary would the the treasury, where anyone (for now) would be able to mint an NFT and could request a `spendProposal` for a house(ID). In the future this would be with verified roles and identities or specific authorities on the platform. 

- Would need to tag in @da-bao-jian for the NFT part as he is working on that that matter. But yes the fund that commited can be used `first-in funds` way. So the investors that first bonded are first in line.  When succesful the house and the treasury makes the payment to the beneficiary. And indeed when the fund is unsuccessful we burn the NFT ( not public function) 
- For the currency used, right now the currency are DEV units in the template-node this could be changed to USD/EUR/JPY/DAI ( As an example)
