### ISSUE TITLE
Testing the chain m-1 with polkadot.js ( testing done by 2 people)

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fair-squares#66]

**Comment by ilhanu** [comment]
**Based on the roles-pallet:**

The extrinsic reads roleModule, housingFundModule —> These can be named roles and housingFund


1. We can create a role, but we cannot destroy it? Users should be albe to get rid of a role
2. After setting a role, I cannot check in the chain state what my role is ? —> Chain state —> Role-module —> getRole
3. WaitingList should maybe be more descriptive —> RoleApprovalList
4. In the log it's nice we can select per AccountID, but the roles should not keep up with the assets, talking about nftindex.

  [
    {
      accountId: 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
      nftIndex: []
      age: 50
    }
  ]

5. Set-manager gives me badOrigin error in all possible ways

**Comment by ilhanu** [comment]
In the housingFund

1. I can contribute to the housing found with a fresh dev chain `cargo run --release -- --tmp --dev` with out taking any role. 
 Also if In take another role I can contribute. Don't understand how our tests are passing ? Think we haven't created one where we don't want an other role than the investors to fund. or that if you have no role set you can't fund at all.
2. Would be nice to also have some cross testing with other modules the example above could save us a lot of time when in the future we would add new features.

**Comment by MrishoLukamba** [comment]
5. set_manager was changed as we detected that during testing,

**Comment by letodunc** [comment]
Code pushed concerning the point 1. of housing fund. The housing_fund pallet uses the roles pallet to check if an investor is calling contribute or withdraw methods.

**Comment by ilhanu** [comment]
- [ ] in `housingFundModule.fundBalance` contributed is the metric that would count when an asset it bought from the fund? If so this should not be registered under the housingFundModule, but rather the history of the houseId @letodunc 
- [ ] rename to `SetRole` instead of `CreateAccount` as the account is easily misunderstood for accountId @ndkazu 
- [ ] in `account_approval` it would be more real and future-ready if  like a receipt, so if a role verifier gives green light for a role, it also has a mandatory proof section.
- [ ] roles maybe in small caps instead of just caps @ilhanu
