### ISSUE TITLE
Remove investor share computational in housing_fund pallet

### ISSUE THREAD

**Issue by letodunc** [Fair-Squares/fair-squares#90]
The share of investors in the housing_fund is updated each time a contribution or a withdraw is done.
This share should be calculated when needed.

The pallet must not compute anymore the share when a contribution or a withdraw is done.
- Remove the share field from the contribution struct
- Remove the call of _update_contribution_share_ from _contribute_to_fund_ and _withdraw_fund_
- Remove _update_contribution_share_ from functions.rs
- Update the tests and benchmarking

**Comment by ndkazu** [comment]
It is important to determine when/where the share is/will be needed before taking a final decision:
- It will be needed when selecting a group of investors as owners of a given asset. At this moment all investor's shares need to be available to the algorithm through designated storage. If we are not calculating the shares in the housing_fund, we will be doing the same computation during future owner selection.
I think this needs to be discussed.

**Comment by letodunc** [comment]
The computation of the share is done at each contribution and withdraw for all the investors. It's some heavy work that can be done when needed from the investor's contribution and the amount in the fund. It's a similar change as the total amount of the fund that is calculated now instead of stored in the fund. A method giving the share of each investor will be called when it's needed. This change will greatly reduce the load on the blockchain.

**Comment by ndkazu** [comment]
I don't Know:
we should also consider the nature of the platform. it's won't be a Dex/Defi platform where you have several contributions/withdraws by one account in a hours/days (this amount of transactions would actually be suspicious)
 
- The algorithm needs to call the share calculation method on  ALL investors each time it is invoked
VS
- Calculation occurs during any transaction between the fund and an account.
The balance tilt does not appear so clear to me...

**Comment by ilhanu** [comment]
agreed this is only foe the total share to the fund, these percentages dont need be calculated on chain.
